originjs/oss-evaluation-service

controllers/downloadCount.js
models/PackageDownloadCount.js
routes/sync.js
service/downloadCountsService.js

add syncDownloadCount function

feat(downloadCount): add syncDownloadCount function

---

controllers/opendigger.js
controllers/scorecard.js
models/Scorecard.js
routes/sync.js
util/error.js

fix: fix typo of "erorr"
feat: add integration for scorecard

feat: add integration for scorecard

---

controllers/compass.js
controllers/scorecard.js
models/CompassActivity.js
models/GithubProjects.js
routes/sync.js

1. remove some unused import
2. add two entity class: CompassActivity and GithubProjcets for ORM operations
3. add compass data sync function

Add compass data sync function

---

.gitignore
controllers/packageSize.js
models/PackageSizeDetail.js
models/PackageSizeInfo.js
package.json
pnpm-lock.yaml
routes/sync.js
service/getPackageSizeService.js

feat: add syncPackageSize function

---

controllers/packageSize.js
models/PackageSizeDetail.js
models/ProjectPackages.js
routes/sync.js
service/getPackageSizeService.js

feat: add syncGitHubProjectPackageSize function

feat: add syncGitHubProjectPackageSize function

---

controllers/downloadCount.js
models/PackageDownloadCount.js
models/ProjectPackage.js
models/weekOfMonth.js
routes/sync.js
service/downloadCountsService.js
service/weekOfMonthService.js

update syncDownloadCount function

feat(downloadCount): update syncDownloadCount function

---

service/downloadCountsService.js

fix field name correspondence bug

fix(downloadCount): fix field name correspondence bug

---

controllers/compass.js
routes/sync.js

fix: check project haven been saved
feat: add incremental integration control
feat: add spice parameter

update compass update function

---

controllers/downloadCount.js

fix(downloadCount): Request error to stop running

---

controllers/downloadCount.js
routes/sync.js

feat(downloadCount): add condition packageName 

---

controllers/downloadCount.js
routes/sync.js

update sync downloadCount function

fix(downloadCount): update sync downloadCount function

---

controllers/downloadCount.js
package.json
pnpm-lock.yaml
routes/sync.js

feat(downloadCount): update downloadCount function

---

controllers/downloadCount.js
tests/week.test.js
util/weekOfYearUtil.js

fix downloadCountJson null element bug

fix(downloadCount): fix downloadCountJson bug

---

controllers/benchmark.js
models/Benchmark.js
routes/sync.js
util/database.js

API added:
- /benchmark/syncBenchmarkHandler
sync test score for a single benchmark
- /benchmark/getPatchId/getPatchId
Acquire a random patch ID for your patch to identify your data from former or other integration.
- /benchmark/bulkCreate/bulkAddBenchmarkHandler
- sync test score from an array of benchmark

feat: add data save API

---

packages/data-orm/index.js
packages/data-orm/util/database.js
packages/integration/controllers/benchmark.js
packages/integration/models/Benchmark.js
packages/integration/package.json
packages/integration/routes/sync.js
packages/website/package.json
pnpm-lock.yaml

Add API for score update, score now can be updated for the same data patch.

feat: improve performance input API

---

packages/integration/controllers/documentScore.js
packages/integration/models/CncfDocumentScore.js
packages/integration/routes/sync.js

add cncf document score integration function.
document score checks collections: changelog, contributing, readme, website

[integration]feat: add cncf document score integration function

---

packages/api-server/routes/softwareEcology.js
packages/api-server/service/softwareEcology.js

add  softwareEcology api getSoftwareCompassActivity

feat(softwareEcology): add  softwareEcology api

---

packages/api-server/service/softwareEcology.js

update getSoftwareMaturity function

feat(softwareEcology): update getSoftwareMaturity function

---

packages/api-server/service/softwareEcology.js

update getSoftwareCompassActivity function

feat(softwareEcology): update getSoftwareCompassActivity function

---

packages/api-server/routes/softwareEcology.js
packages/api-server/service/softwareEcology.js

update softwareEcology function

feat(softwareEcology): update softwareEcology function

---

packages/api-server/service/softwareEcology.js

update getSoftwareEcologyOverview getSoftwareActivity function

feat(softwareEcology): update getSoftwareEcologyOverview getSoftwareActivity function

---

packages/integration/bin/www.js

feat:console print service url

[integration]feat:console print service url

---

packages/api-server/vercel.json

Enabling CORS

---

packages/data-model/models/EvaluationModel.js
packages/integration/controllers/benchmark.js
packages/integration/controllers/evaluate.js

feat: add performance score calculation

feat: add performance score calculation

---

packages/shared-components/src/api/HttpRequest.ts
packages/shared-components/src/api/SearchSoftware.ts
packages/website/src/api/HttpRequest.ts
packages/website/src/api/SoftwareDetails.ts

opt: support custom background service url

opt: support custom background service url

---

package.json
packages/shared-components/package.json
packages/shared-components/src/components/SearchSoftware.vue
packages/website/src/api/SoftwareDetails.ts
packages/website/src/views/SoftwareDetails.vue

feat: benchmark result

---

packages/website/src/api/SoftwareDetails.ts
packages/website/src/views/SoftwareDetails.vue

add data of SonarCloud Scan #141

feat(softwareDetail): add data of SonarCloud Scan

---

packages/shared-components/src/api/SearchSoftware.ts
packages/shared-components/src/components/SearchSoftware.vue
packages/website/src/api/SoftwareDetails.ts
packages/website/src/views/SoftwareDetails.vue

feat: support search software by tech stack

---

packages/website/src/views/SoftwareDetails.vue

Fix compare favorites being obscured

fix: Fix compare favorites being obscured

---

packages/website/src/views/CompareProject.vue

fix: comparison interface refresh error

---

packages/website/src/api/utils.ts
packages/website/src/components/ProjectsCompare.vue
packages/website/src/views/SoftwareDetails.vue

add data of SonarCloud Scan and change css styles #141

feat(softwareDetail): add data of SonarCloud Scan and change css styles

---

packages/shared-components/src/components/SearchSoftware.vue
packages/shared-components/src/components/index.ts
packages/shared-components/src/main.ts
packages/website/src/components/ProjectsCompare.vue
packages/website/src/views/SoftwareDetails.vue

feat: add remove button for benchmark compared software

---

packages/integration/controllers/compass.js
packages/integration/routes/sync.js

feat: reconstruct compass interface and add integration timer
fix: eslint error

feat: reconstruct compass interface and add integration timer

---

packages/data-model/models/PackageDownloadCount.js
packages/integration/controllers/downloadCount.js

feat(PackageDownloadCount): add projectId filed

---

packages/shared-components/src/components/SearchSoftware.vue
packages/website/src/App.vue
packages/website/src/components/ProjectsCompare.vue
packages/website/src/main.ts

fix: style conflict between search box and projects compare

---

packages/data-model/models/CncfDocumentScore.js
packages/integration/controllers/compass.js
packages/integration/controllers/documentScore.js

feat: reconstruct documentScore interface and add integration timer
fix: compass error

feat: reconstruct documentScore interface and add integration timer and fix compass error

---

packages/website/src/components/CompareFavorites.vue
packages/website/src/views/SoftwareDetails.vue

fix: align remove icon

---

packages/website/uno.config.ts

feat(softwareDetail): add safelist

---

packages/api-server/service/softwareDetailService.js
packages/api-server/service/softwareEcology.js
packages/website/src/api/SoftwareDetails.ts
packages/website/src/views/SoftwareDetails.vue

feat: display the package name in the package size area

---

packages/api-server/service/softwareDetailService.js
packages/api-server/service/softwareEcology.js
packages/shared-components/src/api/utils.ts
packages/shared-components/src/components/ProjectsCompare.vue
packages/website/src/api/utils.ts
packages/website/src/views/SoftwareDetails.vue

[fix: NPM weekly download volume displayed as empty](https://github.com/originjs/oss-evaluation-service/commit/15207a7498ad7e8eb331662970f75548967b537e)
[feat: display performanceScore](https://github.com/originjs/oss-evaluation-service/commit/1f512b9c3fd1c6ba0adb1d4c2ed0f3595c021b5a)
[fix: tokilo function](https://github.com/originjs/oss-evaluation-service/commit/89ce73e13e77bd34fb27b9febc8885b47e05ca3f)
[Resolve conflicts](https://github.com/originjs/oss-evaluation-service/commit/46420cad85aa0f4ff382b79d4edc29e50c06ac06)

feat: formate display

---

packages/integration/controllers/documentScore.js
packages/website/src/views/SoftwareDetails.vue

fix: document score display typo
fix: document changelog calculate error

Fix document score integration error and display type

---

packages/api-server/src/services/HomeService.ts
packages/shared-components/src/api/SearchSoftware.ts
packages/shared-components/src/components/CompareFavorites.vue
packages/shared-components/src/components/ProjectsCompare.vue
packages/shared-components/src/components/SearchSoftware.vue
packages/shared-components/src/components/SoftwareDetails.vue
packages/website/package.json
packages/website/src/components/AppHeader.vue
packages/website/src/views/CompareProject.vue
packages/website/src/views/Home.vue
pnpm-lock.yaml

feat: optimize software comparing

---

packages/shared-components/src/router/index.ts

opt: add projects compare dev page

opt: add projects compare dev page

---

packages/api-server/src/services/ProjectDetailService.ts
packages/data-model/models/SonarCloudProject.js
packages/integration/controllers/sonarCloud.js
packages/integration/routes/sync.js

fix: activity api returns null

---

packages/api-server/src/services/ProjectDetailService.ts
pnpm-lock.yaml

feat: returns null when there is no sonarCloud data

---

packages/shared-components/components.d.ts
packages/shared-components/src/components/ProjectsCompare.vue
packages/website/src/views/CompareProject.vue
packages/website/src/views/SoftwareDetails.vue
pnpm-lock.yaml

Optimize compare page

---

packages/integration/controllers/sonarCloud.js

fix: sonarcloud scan err because of c/c++ code

---

packages/shared-components/components.d.ts
packages/shared-components/package.json
packages/shared-components/src/components/ProjectsCompare.vue
pnpm-lock.yaml

feat: show diff in compare page

---

packages/api-server/src/services/TrendService.ts
packages/shared-components/src/components/SoftwareRank.vue

feat(softwareRank): add softwarerank data

---

packages/shared-components/components.d.ts
packages/shared-components/src/components/SoftwareRank.vue

feat(softwareRank): add softwarerank pagination

---

packages/api-server/src/controllers/Project.ts
packages/api-server/src/services/HomeService.ts
packages/api-server/src/services/ProjectDetailService.ts
packages/api-server/src/utils/result.ts

fix: unable to search for software without npm packages

---

packages/api-server/src/interfaces/SoftwareInfo.ts
packages/shared-components/src/components/SoftwareDetails.vue

:sparkles: feat: url links to sonarCloud reports

---

packages/shared-components/components/projects-compare/ProjectsCompare.vue

fix: repo name display

---

packages/data-model/index.js
packages/data-model/models/GithubProjectsStargazersTrend.js
packages/integration/controllers/projectStarGazersTrend.js
packages/integration/routes/sync.js

add syncStargazersTrend function

feat(softwareRank): add syncStargazersTrend function

---

packages/website/uno.config.ts

fix: unocss custom icon display

---

packages/shared-components/components/projects-compare/ProjectsCompare.vue

fixed projects compare page project order
fix #231

fix: fixed projects compare page project order(fix #231)

---

packages/shared-components/components/software-rank/SoftwareRank.vue
packages/website/src/views/SoftwareRank.vue

update getMore function and change css style

feat(softwareRank): update getMore function and change css style

---

packages/shared-components/components/software-rank/SoftwareRank.vue

fix(softwareRank): loading bug

---

packages/integration/controllers/compass.js

Add deduplication logic for Compass integrated data for fix the issue of duplicate unique keys update error in integration

fix: compass integration error 

---

packages/api-server/src/services/ProjectDetailService.ts
packages/api-server/src/services/TrendService.ts
packages/shared-components/components/software-details/SoftwareDetails.vue

feat(softwareDetail): add data of github star trend

---

packages/api-server/src/services/TrendService.ts

fix the problem of new data added every month

fix(softwareRank): fix the problem of new data added every month

---

packages/shared-components/components/projects-compare/ProjectsCompare.vue

fix(projectCompare): openRank tips error

---

packages/shared-components/components/benchmark-compare/BundlerBenchmark.vue
packages/shared-components/components/benchmark-compare/FrameworkBenchmark.vue
packages/shared-components/components/benchmark-compare/TestFrameworkBenchmark.vue

benchmark background color calculation

fix: benchmark background color calculation

---

packages/integration/controllers/projectCodeSize.js
packages/integration/package.json

fix projects with empty code size

---

packages/api-server/src/controllers/Project.ts
packages/api-server/src/controllers/benchmark.ts
packages/api-server/src/services/BenchmarkService.ts
packages/api-server/src/services/ProjectDetailService.ts
packages/shared-components/api/BenchmarkService.ts
packages/shared-components/components/benchmark-compare/BundlerBenchmark.vue
packages/shared-components/components/benchmark-compare/FrameworkBenchmark.vue
packages/shared-components/components/benchmark-compare/TestFrameworkBenchmark.vue

list of projects by subtechnology stack

fix: list of projects by subtechnology stack

---

packages/api-server/package.json
packages/api-server/src/services/ProjectDetailService.ts
pnpm-lock.yaml

:bug: fix(benchmark): benchmark data is not rounded.

---

packages/api-server/src/services/TrendService.ts

fix(softwareRank): add array type

---

packages/shared-components/components/software-details/SoftwareDetails.vue

fix: Fixed the issue where an empty box is displayed when the technology stack value is null.

---

packages/shared-components/components/software-details/SoftwareDetails.vue

feat: Optimize the display effect and position of the technology stack categorization.

---

packages/api-server/src/services/BenchmarkService.ts
packages/api-server/src/services/ProjectDetailService.ts

:bug: fix: bundle software benchmark data is 0

---

packages/shared-components/components/software-details/SoftwareDetails.vue
packages/shared-components/components/software-rank/SoftwareRank.vue

the github star trend chart points are too dense

fix(softwareRank): the github star trend chart points are too dense

---

packages/api-server/src/app.ts
packages/api-server/src/services/ProjectDetailService.ts

fix: download error

---

packages/shared-components/components/software-rank/SoftwareRank.vue

add removeEventListener fix#299

fix(softwareDetail): add removeEventListener fix#299

---

packages/shared-components/components/projects-compare/ProjectsCompare.vue

Add tips about activity  to the software comparison interface.
Auto format.
close #306

:speech_balloon:feat: Add tips about activity  to the software comparison interface.

---

packages/shared-components/components/benchmark-compare/ApplyNewProjectBenchmarkDialog.vue
packages/shared-components/components/benchmark-compare/ChooseBenchmarkDialog.vue
packages/shared-components/components/benchmark-compare/ChooseProjectsDialog.vue
packages/shared-components/components/benchmark-compare/FrameworkBenchmark.vue

feat: add unit and multiple of base

---

packages/shared-components/components/benchmark-compare/FrameworkBenchmark.vue

feat: support remove benchmark compare project

---

packages/api-server/src/services/ProjectDetailService.ts

fix softwareActivity data
close #310

fix(softwareDetail): fix softwareActivity data

---

packages/shared-components/components/software-rank/SoftwareRank.vue

update contributorCount format

feat(softwareDetail): update contributorCount format

---

packages/api-server/src/interfaces/SoftwareInfo.ts
packages/api-server/src/services/BenchmarkService.ts
packages/shared-components/components/benchmark-compare/ChooseProjectsDialog.vue

1. Add open source project version
2. Supported Search
3. Support full selection, inverse selection, single selection

fix: add open source project version
